### ISSUE TITLE
About pytorch version.

### ISSUE THREAD

**Issue by a18700** [qiqihaer/RandLA-Net-pytorch#8]
Hello,

I got errors below, when to experiment with your codes.

I think this is a pytorch version issue, thereby i want to know the implementation settings.

---

/workspace/gt_cvpr/gt_codes/NewBaseLine/RandLA-Net-pytorch/RandLANet.py:264: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  reducing_list = torch.range(0, cfg.num_classes).long().cuda()
Traceback (most recent call last):
  File "main_SemanticKITTI.py", line 209, in <module>
    train(start_epoch)
  File "main_SemanticKITTI.py", line 189, in train
    train_one_epoch()
  File "main_SemanticKITTI.py", line 110, in train_one_epoch
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

**Comment by qiqihaer** [comment]
> Hello,
> 
> I got errors below, when to experiment with your codes.
> 
> I think this is a pytorch version issue, thereby i want to know the implementation settings.
> 
> /workspace/gt_cvpr/gt_codes/NewBaseLine/RandLA-Net-pytorch/RandLANet.py:264: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
> reducing_list = torch.range(0, cfg.num_classes).long().cuda()
> Traceback (most recent call last):
> File "main_SemanticKITTI.py", line 209, in
> train(start_epoch)
> File "main_SemanticKITTI.py", line 189, in train
> train_one_epoch()
> File "main_SemanticKITTI.py", line 110, in train_one_epoch
> loss.backward()
> File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
> torch.autograd.backward(self, gradient, retain_graph, create_graph)
> File "/opt/conda/lib/python3.7/site-packages/torch/autograd/**init**.py", line 99, in backward
> allow_unreachable=True) # allow_unreachable flag
> RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

CUDA9.0, Pytorch1.1
